# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dailyschedule.ui'
#
# Created by: PyQt5 UI code generator 5.10
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DailySchedule(object):
    def setupUi(self, DailySchedule):
        DailySchedule.setObjectName("DailySchedule")
        DailySchedule.resize(581, 391)
        DailySchedule.setGeometry(QtCore.QRect(230, 30, 581, 391))
        self.label = QtWidgets.QLabel(DailySchedule)
        self.label.setGeometry(QtCore.QRect(20, 10, 81, 21))
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(DailySchedule)
        self.tableWidget.setGeometry(QtCore.QRect(10, 50, 561, 341))
        self.tableWidget.setRowCount(16)
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setHorizontalHeaderLabels(["Time", "Meetings"])
        self.tableWidget.setVerticalHeaderLabels([""]*16)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(4, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(5, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(6, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(7, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(8, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(9, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(10, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(11, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(12, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(13, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(14, 0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setItem(15, 0, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(265)
        self.tableWidget.horizontalHeader().setHighlightSections(True)

        self.retranslateUi(DailySchedule)
        QtCore.QMetaObject.connectSlotsByName(DailySchedule)

    def retranslateUi(self, DailySchedule):
        _translate = QtCore.QCoreApplication.translate
        DailySchedule.setWindowTitle(_translate("DailySchedule", "Frame"))
        self.label.setText(_translate("DailySchedule", "Date"))
        __sortingEnabled = self.tableWidget.isSortingEnabled()
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.item(0, 0)
        item.setText(_translate("DailySchedule", "9:00 am"))
        item = self.tableWidget.item(1, 0)
        item.setText(_translate("DailySchedule", "9:30 am"))
        item = self.tableWidget.item(2, 0)
        item.setText(_translate("DailySchedule", "10:00 am"))
        item = self.tableWidget.item(3, 0)
        item.setText(_translate("DailySchedule", "10:30 am"))
        item = self.tableWidget.item(4, 0)
        item.setText(_translate("DailySchedule", "11:00 am"))
        item = self.tableWidget.item(5, 0)
        item.setText(_translate("DailySchedule", "11:30 am"))
        item = self.tableWidget.item(6, 0)
        item.setText(_translate("DailySchedule", "12:00 pm"))
        item = self.tableWidget.item(7, 0)
        item.setText(_translate("DailySchedule", "12:30 pm"))
        item = self.tableWidget.item(8, 0)
        item.setText(_translate("DailySchedule", "1:00 pm"))
        item = self.tableWidget.item(9, 0)
        item.setText(_translate("DailySchedule", "1:30 pm"))
        item = self.tableWidget.item(10, 0)
        item.setText(_translate("DailySchedule", "2:00 pm"))
        item = self.tableWidget.item(11, 0)
        item.setText(_translate("DailySchedule", "2:30 pm"))
        item = self.tableWidget.item(12, 0)
        item.setText(_translate("DailySchedule", "3:00 pm"))
        item = self.tableWidget.item(13, 0)
        item.setText(_translate("DailySchedule", "3:30 pm"))
        item = self.tableWidget.item(14, 0)
        item.setText(_translate("DailySchedule", "4:00 pm"))
        item = self.tableWidget.item(15, 0)
        item.setText(_translate("DailySchedule", "4:30 pm"))
        self.tableWidget.setSortingEnabled(__sortingEnabled)

